#!/bin/bash
##Created by Arya Pramudika 2023-08-09
  
# Delete VM Proxmox by name
name=$1

##Find vmid by name
vmid=$(qm list | grep "$name" | awk '{print $1}')

## Delete VM
qm stop ${vmid}
qm destroy ${vmid}
